# A workflow that runs [cargo-flake](https://github.com/blt/cargo-flake) across
# our tests, benchmarks included.
#
# This is a nighly flow as the cargo-flake run is time consuming.
name: cargo_flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  AUTOINSTALL: true
  VERBOSE: true
  CI: true
  DEBIAN_FRONTEND: noninteractive
  RUSTFLAGS: "-D warnings"

jobs:
  hack:
    runs-on: [self-hosted, linux, x64, general]
    name: Cargo Flake
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v3.0.9
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: cargo install cargo-flake
      - run: make slim-builds
      - run: cargo flake --features 'default benches metrics-benches remap-benches'
      - name: Stop sccache
        run: sccache --stop-server
